application: playlist-arunjit
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /app
  static_dir: app
  login: admin

- url: /(user|playlist|song)?.*
  script: main.application
  login: admin


libraries:
- name: jinja2
  version: latest
